boot.o: boot.S multiboot.h x86_desc.h types.h
interrupts.o: interrupts.S x86_desc.h types.h
x86_desc.o: x86_desc.S x86_desc.h types.h
fileSystemModule.o: fileSystemModule.c fileSystemModule.h types.h \
  system_calls.h terminal.h keyboard.h lib.h
i8259.o: i8259.c i8259.h types.h lib.h
interrupt_table.o: interrupt_table.c interrupt_table.h x86_desc.h types.h \
  lib.h i8259.h interrupts.h
kernel.o: kernel.c multiboot.h types.h x86_desc.h lib.h i8259.h debug.h \
  interrupt_table.h rtc.h keyboard.h paging.h terminal.h \
  fileSystemModule.h interrupts.h system_calls.h scheduling.h
keyboard.o: keyboard.c keyboard.h types.h lib.h i8259.h x86_desc.h \
  system_calls.h terminal.h
lib.o: lib.c lib.h types.h i8259.h terminal.h keyboard.h scheduling.h \
  system_calls.h
paging.o: paging.c paging.h types.h
rtc.o: rtc.c rtc.h types.h i8259.h lib.h system_calls.h terminal.h \
  keyboard.h scheduling.h
scheduling.o: scheduling.c scheduling.h types.h system_calls.h terminal.h \
  keyboard.h i8259.h lib.h paging.h x86_desc.h
system_calls.o: system_calls.c x86_desc.h types.h paging.h lib.h \
  fileSystemModule.h system_calls.h terminal.h keyboard.h scheduling.h \
  rtc.h
terminal.o: terminal.c terminal.h types.h keyboard.h lib.h system_calls.h \
  i8259.h paging.h scheduling.h
