name: Make

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install make
      run: sudo apt update && sudo apt install make && sudo apt install make && sudo apt install grub2-common

    - name: Build
      run: make

